### ISSUE TITLE
Got No such module for the 1.6.4 release

### ISSUE THREAD

**Issue by nourahassan** [bugfender/BugfenderSDK-iOS#43]
After doing `carthage update` to get latest version 1.6.4, it downloads the binary:

`Downloading BugfenderSDK-iOS.framework binary at "1.6.4"` 

Xcode gives error `No such module on 'BugfenderSDK'`on `import BugfenderSDK`.

**Comment by jgimenez** [comment]
Hi @nourahassan , usually this happens when after downloading the binary you've not integrated the library in your project yet. You need to install it as a static framework, you have the step-by-step instructions on the README file. Xcode sometimes can't find a module when there really is one because of caching issues. You might want to try cleaning and rebuilding your whole project.

If after trying these steps still doesn't work, please contact us on support, we can take a look at your particular project details

**Comment by nourahassan** [comment]
I cleaned and removed DerivedData and same issue, also I already have the version 1.6.3 working. If I just set the version in Cartfile to `1.6.3` and run `carthage update`. My project builds successfully.

I think you need to check the binary for last release. I compared it with the previous one and it has the `BugfenderSDK` file not executable. Not sure if that is the problem.

**Comment by RubenVot** [comment]
Hi, in the version 1.6.4 we have introduced some changes in the modulemap file. I think this could be the cause of the module error. However we didn’t detect this problem during the testing. Let us check again and come back with an answer. 
Thanks for the feedback!

**Comment by RubenVot** [comment]
Hi @nourahassan   
We have changed the modulemap, you should be able to install 1.6.4 using Carthage now. 
Let us know if you get any trouble.

**Comment by nourahassan** [comment]
Yes, it is fixed now. Thanks!

**Comment by RubenVot** [comment]
Thank you for the feedback! It helps us a lot.
