### ISSUE TITLE
Error: Bugfender SDK does not specify a Swift version

### ISSUE THREAD

**Issue by bhavinmdesai** [bugfender/BugfenderSDK-iOS#44]
_Please make sure to inform your SDK version number_.

Bugfender SDK 1.6.3

**We're getting following error at compile time:**

> `BugfenderSDK` does not specify a Swift version and none of the targets (`TestApp` and `TestAppInt`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**FYI this is what we've written in our podfile:**
> pod 'BugfenderSDK', '1.6.3'

**Swift Version: 4.2
xCode Version: 10.1
Our project is a mixture of Swift and ObjC**

Let me know if you need more information.

**Comment by RubenVot** [comment]
Hi @bhavinmdesai, 
I think your project settings should set a Swift version and this will be inherited to all the targets in the project. 
Anyway, I will check with the team if it may sense to add the swift version to the podspec

**Comment by RubenVot** [comment]
Hi @bhavinmdesai, 

After discussing with the team, we don't think we should add a specific swift version to the Podspec because BugfenderSDK already supports different Swift Versions (you can check it in the file Bugfender.swift file). Your project should specify which Swift version are you using. 

The error you are getting is caused because your target didn't setup a Swift Version. This might happen if you create an ObjC project and you use: 
```
 pod 'BugfenderSDK' // Adds swift code. Swift environment needs to be available
```
Instead of: 
```
pod 'BugfenderSDK/ObjC' // Only objc
```
You mentioned that your project is a Objc/Swift hybrid however the error you got states _"none of the targets (TestApp and TestAppInt) integrating it have the SWIFT_VERSION attribute set"_. 

The SWIFT_VERSION property should be added to your project automatically when you add Swift classes and it should appear in your target properties: 
<img width="1043" alt="Screen Shot 2019-03-26 at 19 52 07" src="https://user-images.githubusercontent.com/1536171/54998699-5f906a00-5001-11e9-93b4-2761fb694f94.png">

Please, review you Target configuration and let us know if you have further doubts.
