### ISSUE TITLE
Failed to load Info.plist from bundle at path

### ISSUE THREAD

**Issue by basememara** [bugfender/BugfenderSDK-iOS#47]
I using the latest Bugfender 1.6.6 via Carthage:
`binary "https://raw.githubusercontent.com/bugfender/BugfenderSDK-iOS/master/BugfenderSDK.json" ~> 1.6`

The project compiles, but when it tries to launch the app in the simulator, I get an Xcode alert saying:
`The app could not be installed at this time. Failed to load Info.plist from bunch at path .../Frameworks/BugfenderSDK.framework.`

Sure enough, there is no `Info.plist` in my `/Carthage/Build/iOS/BugfenderSDK.framework/` directory. However, all my other Carthage frameworks do have an `Info.plist` file. I tried cleaning the solution, restarting Xcode, erasing the simulator, quitting it, etc but nothing. And indeed I have Bugfender in the linked libraries not embedded.

So my solution was so copy one of the other Info.plist, adjust it and place in the `BugfenderSDK.framework` directory, and it worked! I think you need an Info.plist in the framework source. I hope this helps.

[Info.plist.zip](https://github.com/bugfender/BugfenderSDK-iOS/files/3439542/Info.plist.zip)

**Comment by RubenVot** [comment]
Hi @basememara! Thanks a lot for your proactivity sending us this info.plist 
One question, are you using the new Xcode Beta version in OSX Catalina?

**Comment by basememara** [comment]
No I’m not using a beta, using Xcode 10.3.

**Comment by RubenVot** [comment]
Hi @basememara the issue you got usually happens when you embed the framework instead of just link it. 
Go to the target settings and add BugfenderSDK to the **Linked frameworks** and ensure the framework is not included in the **Embedded Binaries**
Closing for now as we are pretty sure that's the issue. 
Feel free to ping back if it is not solved. Thanks for your feedback!

**Comment by basememara** [comment]
Thanks @RubenVot, but this is certainly not the issue. I realize this is a symptom of making that mistake, but as others have mentioned, this step was followed correctly and indeed have added it to Linked frameworks.

Are you trying it with a Swift project via Carthage? Once you wire it together, it might compile ok the first time. Try cleaning and you might see the error.

**Comment by RubenVot** [comment]
Hi @basememara, 
we have different test projects with every possible installation configuration that we run prior to every release. Also, we have been doing tests with Xcode 11 and Swift and the only times that we have detected this issue was because BugfenderSDK was embedded as a binary. 
There used to be a bug in Xcode that might cause this issue but, as far as I know, it was fixed a while ago by Apple. 
Anyway, I will report it internally and we will run new tests. 
Thanks for your feedback
