### ISSUE TITLE
Catalyst Support

### ISSUE THREAD

**Issue by mcmurrym** [bugfender/BugfenderSDK-iOS#49]
We would like to take our iOS app to the Mac this fall, it would be great if Bugfender worked with Mac Catalyst apps when the time comes.

**Comment by RubenVot** [comment]
Hi @mcmurrym, 
We are actually investigating right now how can we offer support for the new features in iOS including Catalyst, SwiftUI and others :) 
More news to come soon. Thanks a lot for using Bugfender and taking your time to send us your feedback.

**Comment by RubenVot** [comment]
We have advanced in the manual installation of BugfenderSDK creating a new xcframework.
Cocoapods discussing Catalyst support here https://github.com/CocoaPods/CocoaPods/issues/8892 
Carthage discussing here https://github.com/Carthage/Carthage/issues/2799

**Comment by RubenVot** [comment]
Hi @mcmurrym , 
We have released a xcframework in a new branch: https://github.com/bugfender/BugfenderSDK-iOS/tree/feature/1.8.0-beta
Our plan is to invite to test all the users that have requested project Catalyst support in the past months.  
In case some feedback comes back we will adjust, otherwise the branch 1.8.0 will be merged to master :)
